# prettier-ignore
controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login:
    path: /api/login

api_refresh_token:
    path: /api/token/refresh
