#prettier-ignore

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $uploadsPath: "%kernel.project_dir%/public/uploads"
  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  App\Listeners\AuthenticationSuccessListener:
    arguments: ["%lexik_jwt_authentication.token_ttl%"]
    tags:
      - {name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccess, priority: -2}
  App\Listeners\RefreshedTokenListener:
        arguments: ['%gesdinet_jwt_refresh_token.ttl%']
